version: '3.8'

services:
  discord-welcome-bot:
    build: .
    container_name: discord-welcome-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_WELCOME_CHANNEL_ID=${DISCORD_WELCOME_CHANNEL_ID}
      - DISCORD_WELCOME_GIF=${DISCORD_WELCOME_GIF}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
